### ISSUE TITLE
Run-time error '50003': unexpected error

### ISSUE THREAD

**Issue by cuixiping** [dnomd343/HRD_Game#1]
Run-time error '50003': unexpected error

![Run-time error 50003](https://user-images.githubusercontent.com/1104492/220801605-d3f72643-943d-4fc7-b94f-430c986f336f.png)

步骤:
1. 点"经典布局"
2. 点"确定"
3. 看到如上报错

系统环境:
win7, x64

**Comment by dnomd343** [comment]
感谢反馈，这个问题印象中是部分精简系统导致的，表现为自定义 ICON 的窗口出现崩溃。

我目前手头没有 VB 环境可以复现测试，但之前为了解决这个问题有编译另一个版本，具体修复代码已经找不到了，不过编译导出的 exe 文件还在。您可以下载这个版本试一下是否正常，如果仍然不行，可以尝试安装 VB6 运行环境补全缺失的系统文件。

[HRD_Game-v2.1-mod.zip](https://github.com/dnomd343/HRD_Game/files/10820332/HRD_Game-v2.1-mod.zip)

[备用链接](https://res.343.re/Share/HRD_Game-v2.1-mod.exe)

文件 SHA1 哈希值：

```
c22135cc4b7109e4f0ab941e27d5976f51bc0d0f  HRD_Game-v2.1.exe
a487fd9f071484222575616b8e20cfd8092afe20  HRD_Game-v2.1-mod.exe
```

解压对比 Release 中的 `v2.1` 版本，是 2020-04-19 重新编译的，没记错的话就是为了解决 50003 报错编译的。

![image](https://user-images.githubusercontent.com/54678581/221082821-bbbfe907-aff9-45fd-9f96-a352a90b91fb.png)

**Comment by cuixiping** [comment]
的确如此, mod版正常运行了. 感谢 👍 💯
